title: 'Data 88: Economic Models Textbook'
author: Eric Van Dusen, Chris Pyles, Angela Guan, Shashank Dalmia, Amal Bhatnagar, Andrei Caprau, Alan Liang, Umar Maniku, Alex McMurry
logo: content/images/econ-models.png
copyright: 2020

repository:
  url: https://github.com/ds-connectors/econ-models-Textbook

launch_buttons:
    binderhub_url: https://mybinder.org
    jupyterhub_url: https://datahub.berkeley.edu

html:
  favicon: content/images/favicon.ico
  use_repository_button: true
